### ISSUE TITLE
Ram Usage Adjustment

### ISSUE THREAD

**Issue by charmedai** [codingstark-dev/burp-suite-pro-mac#2]
Hey, thanks for the burp it works great but it there a way to adjust ram usage or allocate more ram. 

Thanks

**Comment by codingstark-dev** [comment]
@charmedai using -Xmx4g allow the amount of RAM you want to allocate (e.g., 2g for 2GB, 8g for 8GB, etc.).
`"/Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home/bin/java" -Xmx4g "--add-opens=java.desktop/javax.swing=ALL-UNNAMED" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED" "-javaagent:Burploaderv2.jar" "-noverify" "-jar" "burpsuite_pro_v2024.5.1.jar"
`

**Comment by codingstark-dev** [comment]
@charmedai using -Xmx4g allow the amount of RAM you want to allocate (e.g., 2g for 2GB, 8g for 8GB, etc.).
`"/Library/Java/JavaVirtualMachines/jdk-18.0.2.1.jdk/Contents/Home/bin/java" -Xmx4g "--add-opens=java.desktop/javax.swing=ALL-UNNAMED" "--add-opens=java.base/java.lang=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.tree=ALL-UNNAMED" "--add-opens=java.base/jdk.internal.org.objectweb.asm.Opcodes=ALL-UNNAMED" "-javaagent:Burploaderv2.jar" "-noverify" "-jar" "burpsuite_pro_v2024.5.1.jar"
`
